# Generated by Django 5.0.6 on 2024-06-27 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_setor', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('cpf', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nome_pessoa', models.CharField(max_length=25)),
                ('idade', models.IntegerField()),
                ('idsetor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.setor')),
            ],
        ),
    ]
